# Generated by Django 4.1.3 on 2023-03-03 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('power', models.DecimalField(decimal_places=4, max_digits=9)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('produced', models.DecimalField(decimal_places=10, max_digits=13)),
                ('used', models.DecimalField(decimal_places=10, max_digits=13)),
                ('production_meter_reading', models.DecimalField(decimal_places=10, max_digits=15)),
                ('grid_meter_reading', models.DecimalField(decimal_places=10, max_digits=15)),
                ('grid_feed_in', models.DecimalField(decimal_places=10, max_digits=13)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('self_consumption', models.DecimalField(decimal_places=10, max_digits=13)),
                ('grid_consumption', models.DecimalField(decimal_places=10, max_digits=13)),
                ('consumption', models.DecimalField(decimal_places=10, max_digits=13)),
                ('meter_reading', models.DecimalField(decimal_places=10, max_digits=15)),
                ('price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('reduced_price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('grid_price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('saved', models.DecimalField(decimal_places=10, max_digits=13)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.consumer')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.production')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contracts.rate')),
            ],
        ),
    ]
