# Generated by Django 4.1.3 on 2023-03-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[('PM', 'Production Meter'), ('CM', 'Consumption Meter'), ('GM', 'Grid Meter')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=20)),
                ('peak_power', models.IntegerField()),
                ('last_production_reading', models.DateTimeField(null=True)),
                ('last_grid_reading', models.DateTimeField(null=True)),
                ('production_overflow', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('grid_sensor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='producer_grid', to='sensors.sensor')),
                ('production_sensor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='producer', to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('last_reading', models.DateTimeField(null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensors.producer')),
                ('rates', models.ManyToManyField(through='contracts.Contract', to='contracts.rate')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='sensors.sensor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
