# Generated by Django 4.1.3 on 2023-02-04 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('self_consumption', models.DecimalField(decimal_places=10, max_digits=13)),
                ('grid_consumption', models.DecimalField(decimal_places=10, max_digits=13)),
                ('consumption', models.DecimalField(decimal_places=10, max_digits=13)),
                ('meter_reading', models.DecimalField(decimal_places=10, max_digits=15)),
                ('price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('reduced_price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('grid_price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('saved', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('produced', models.DecimalField(decimal_places=10, max_digits=13)),
                ('used', models.DecimalField(decimal_places=10, max_digits=13)),
                ('production_meter_reading', models.DecimalField(decimal_places=10, max_digits=15)),
                ('grid_meter_reading', models.DecimalField(decimal_places=10, max_digits=15)),
                ('grid_feed_in', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('reduced_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('flexible', models.BooleanField(default=False)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('power', models.DecimalField(decimal_places=4, max_digits=9)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
