# Generated by Django 4.1.3 on 2023-01-23 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='production',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensors.producer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.consumer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.rate'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensors.consumer'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.production'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.rate'),
        ),
    ]
